services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      .env
    ports:
      - 8000:8000
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      timeout: 2s
      retries: 10
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

